---

collections:
  - manala.roles
  - name: ansible.netcommon
    version: 2.5.0
  - name: ansible.posix
    version: 1.3.0
  - name: ansible.utils
    version: 2.4.3
  - name: community.general
    version: 4.4.0

roles:
  - src: geerlingguy.swap
    version: 1.0.2